== Introduction

Generic Register Operation Optimizer (`groov`) is a library that abstracts read
and write operations on registers in baremetal embedded systems. Some important
features of `groov` are:

- Abstraction through separation of name and layout: where possible, registers
  and fields are referenced by name and manipulated with strong types rather
  than by poking bits into the layout.
- Awareness of asynchronous operation: read and write operations are not just
  assumed to be synchronous to memory, but are modelled with senders to allow
  for asynchronous event-driven scenarios. Synchronous behaviour is still
  supported since it is a subset of asynchronous behaviour.
- Error handling: the same mechanism that allows read and write operations to be
  asynchronous also provides a path for errors.

== Dependencies

This repository uses https://github.com/cpm-cmake/CPM.cmake[CPM] and a
https://github.com/intel/cicd-repo-infrastructure[common CI/CD infrastructure].

The library dependencies are:

- https://github.com/boostorg/mp11[Boost.MP11]
- https://github.com/intel/cpp-std-extensions[C++ std extensions (`stdx`)]
- https://github.com/intel/cpp-baremetal-senders-and-receivers[Baremetal Senders & Receivers]
